// src/frontend/src/app/dashboard/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useAuth } from '@/components/auth/AuthContext'
import CertificateCard from '@/components/certificates/CertificateCard'
import { apiClient } from '@/api/api-client'
import { useRouter } from 'next/navigation'

interface Certificate {
  id: string | number
  attributes: {
    name: string
    credentialId: string
    issuanceDate: string
    expirationDate?: string
    revoked: boolean
    image?: {
      data?: {
        attributes?: {
          url: string
        }
      }
    }
    achievement?: {
      data?: {
        attributes?: {
          name: string
          description?: string
        }
      }
    }
    issuer?: {
      data?: {
        attributes?: {
          name: string
        }
      }
    }
  }
}

export default function DashboardPage() {
  const { isAuthenticated, isLoading: authLoading } = useAuth()
  const [activeTab, setActiveTab] = useState('all')
  const [certificates, setCertificates] = useState<Certificate[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const router = useRouter()

  useEffect(() => {
    // Redirect if not authenticated
    if (!authLoading && !isAuthenticated) {
      router.push('/login')
    }
  }, [isAuthenticated, authLoading, router])

  useEffect(() => {
    if (isAuthenticated) {
      fetchCertificates()
    }
  }, [isAuthenticated, activeTab])

  const fetchCertificates = async () => {
    setIsLoading(true)
    setError(null)

    try {
      let response

      if (activeTab === 'received') {
        response = await apiClient.getReceivedCertificates()
      } else if (activeTab === 'issued') {
        response = await apiClient.getIssuedCertificates()
      } else {
        response = await apiClient.getUserCertificates()
      }

      setCertificates(response.data || [])
    } catch (err) {
      console.error('Error fetching certificates:', err)
      setError('Failed to load certificates. Please make sure the backend is properly configured.')
    } finally {
      setIsLoading(false)
    }
  }

  const handleDeleteCertificate = async (id: string | number) => {
    try {
      await apiClient.delete(`/api/credentials/${id}`)
      // Refresh the list
      fetchCertificates()
    } catch (error) {
      console.error('Error deleting certificate:', error)
    }
  }

  if (authLoading) {
    return <div className="text-center py-12">Loading...</div>
  }

  if (!isAuthenticated) {
    return null // Will redirect in useEffect
  }

  return (
    <div className="max-w-7xl mx-auto">
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-3xl font-bold">Your Certificates</h1>
      </div>

      <div className="mb-6 border-b border-gray-200">
        <nav className="flex -mb-px">
          <button
            onClick={() => setActiveTab('received')}
            className={`py-2 px-4 border-b-2 font-medium text-sm ${
              activeTab === 'received'
                ? 'border-blue-500 text-blue-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            Received
          </button>
          <button
            onClick={() => setActiveTab('issued')}
            className={`py-2 px-4 border-b-2 font-medium text-sm ${
              activeTab === 'issued'
                ? 'border-blue-500 text-blue-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            Issued
          </button>
          <button
            onClick={() => setActiveTab('all')}
            className={`py-2 px-4 border-b-2 font-medium text-sm ${
              activeTab === 'all'
                ? 'border-blue-500 text-blue-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            All
          </button>
        </nav>
      </div>

      {isLoading ? (
        <div className="text-center py-12">Loading certificates...</div>
      ) : error ? (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
          {error}
        </div>
      ) : certificates.length === 0 ? (
        <div className="text-center py-12 bg-gray-50 dark:bg-gray-800 rounded-lg">
          <p className="text-lg text-gray-600 dark:text-gray-300">
            {activeTab === 'received'
              ? "You haven't received any certificates yet."
              : activeTab === 'issued'
              ? "You haven't issued any certificates yet."
              : "You don't have any certificates yet."}
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {certificates.map((certificate) => (
            <CertificateCard
              key={certificate.id}
              certificate={certificate}
              onExport={() => console.log('Certificate exported')}
              onDelete={() => handleDeleteCertificate(certificate.id)}
              onRevoke={activeTab === 'issued' ? () => fetchCertificates() : undefined}
            />
          ))}
        </div>
      )}
    </div>
  )
}

// src/frontend/pages/dashboard.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useAuthStore } from '~/stores/auth'
import { apiClient } from '~/api/api-client'
import CertificateCard from '~/components/CertificateCard.vue'

definePageMeta({
  middleware: ['auth']
})

interface Certificate {
  id: string
  title: string
  description: string
  issueDate: string
  recipientCount: number
  status: 'active' | 'draft' | 'archived'
  type?: string
  recipient?: {
    name: string
    email: string
  }
  issuer?: {
    name: string
    url: string
  }
}

const authStore = useAuthStore()
const loading = ref(false)
const error = ref<string | null>(null)

const receivedCertificates = ref<Certificate[]>([])
const issuedCertificates = ref<Certificate[]>([])

onMounted(async () => {
  if (!authStore.isAuthenticated) return
  
  loading.value = true
  error.value = null
  
  try {
    // Fetch certificates
    const [receivedResponse, issuedResponse] = await Promise.all([
      apiClient.getReceivedCertificates(),
      authStore.isIssuer ? apiClient.getIssuedCertificates() : Promise.resolve({ data: [] })
    ])

    receivedCertificates.value = receivedResponse.data || []
    issuedCertificates.value = issuedResponse.data || []

    console.log('Received certificates:', receivedCertificates.value.length)
    console.log('Issued certificates:', issuedCertificates.value.length)
  } catch (err) {
    console.error('Error fetching dashboard data:', err)
    error.value = 'Failed to load dashboard data. Please try again.'
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <div class="container mx-auto px-4 py-8">
    <!-- Loading State -->
    <div v-if="loading" class="flex justify-center items-center py-12">
      <div class="w-8 h-8 border-4 border-[#00E5C5] border-t-transparent rounded-full animate-spin"></div>
    </div>

    <!-- Error State -->
    <div v-else-if="error" class="bg-red-50 border border-red-200 rounded-lg p-4 mb-8">
      <p class="text-red-800">{{ error }}</p>
      <button 
        @click="$router.go(0)" 
        class="mt-2 text-sm text-red-600 hover:text-red-800"
      >
        Try Again
      </button>
    </div>

    <template v-else>
      <!-- Received Certificates Section -->
      <div class="mb-12">
        <div class="flex items-center justify-between mb-6">
          <h2 class="text-2xl font-semibold">Received Certificates</h2>
        </div>
        <div v-if="receivedCertificates.length === 0" class="text-center py-12 bg-gray-50 rounded-lg">
          <div class="i-heroicons-inbox w-12 h-12 mx-auto text-gray-400 mb-3"></div>
          <h3 class="text-lg font-medium mb-2">No Certificates Yet</h3>
          <p class="text-gray-600">You haven't received any certificates yet.</p>
        </div>
        <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <CertificateCard 
            v-for="cert in receivedCertificates" 
            :key="cert.id" 
            :certificate="cert"
            :show-recipient="false"
          />
        </div>
      </div>

      <!-- Issued Certificates Section (Only for issuers) -->
      <div v-if="authStore.isIssuer">
        <div class="flex items-center justify-between mb-6">
          <h2 class="text-2xl font-semibold">Issued Certificates</h2>
          <div class="flex items-center gap-4">
            <NuxtLink 
              to="/issue" 
              class="px-4 py-2 bg-[#00E5C5] text-white rounded-full hover:bg-[#00E5C5]/90 transition-colors"
            >
              Issue New
            </NuxtLink>
          </div>
        </div>
        <div v-if="issuedCertificates.length === 0" class="text-center py-12 bg-gray-50 rounded-lg">
          <div class="i-heroicons-document-plus w-12 h-12 mx-auto text-gray-400 mb-3"></div>
          <h3 class="text-lg font-medium mb-2">No Issued Certificates</h3>
          <p class="text-gray-600 mb-4">You haven't issued any certificates yet.</p>
          <NuxtLink 
            to="/issue"
            class="inline-flex items-center px-4 py-2 bg-[#00E5C5] text-white rounded-full hover:bg-[#00E5C5]/90 transition-colors"
          >
            <div class="i-heroicons-plus w-5 h-5 mr-2"></div>
            Issue Your First Certificate
          </NuxtLink>
        </div>
        <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <CertificateCard 
            v-for="cert in issuedCertificates" 
            :key="cert.id" 
            :certificate="cert" 
          />
        </div>
      </div>
    </template>
  </div>
</template>
