// src/frontend/src/app/auth/reset-password/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import apiClient from '@/api/api-client'
import Link from 'next/link'

export default function ResetPasswordPage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const [password, setPassword] = useState('')
  const [passwordConfirmation, setPasswordConfirmation] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState(false)
  const [token, setToken] = useState<string | null>(null)
  
  useEffect(() => {
    // Get code from URL query parameters
    const code = searchParams.get('code')
    if (code) {
      setToken(code)
    } else {
      setError('Reset token is missing. Please check your reset link.')
    }
  }, [searchParams])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (password !== passwordConfirmation) {
      setError('Passwords do not match.')
      return
    }
    
    if (!token) {
      setError('Reset token is missing. Please check your reset link.')
      return
    }
    
    setIsSubmitting(true)
    setError(null)
    
    try {
      await apiClient.post('/api/auth/reset-password', {
        code: token,
        password,
        passwordConfirmation
      })
      setSuccess(true)
      
      // Redirect to login after 3 seconds
      setTimeout(() => {
        router.push('/login')
      }, 3000)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred while resetting password')
      console.error('Password reset error:', err)
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="max-w-md mx-auto py-12 px-4">
      <h1 className="text-3xl font-bold text-center mb-8">Set New Password</h1>
      
      {success ? (
        <div className="bg-green-50 border border-green-200 text-green-800 rounded-md p-4 mb-4">
          <p>Your password has been reset successfully!</p>
          <p>You'll be redirected to the login page in a few seconds.</p>
          <p className="mt-4">
            <Link href="/login" className="text-blue-600 hover:underline">
              Go to login
            </Link>
          </p>
        </div>
      ) : (
        <>
          {error && (
            <div className="bg-red-50 border border-red-200 text-red-800 rounded-md p-4 mb-4">
              {error}
            </div>
          )}
          
          <div className="bg-white dark:bg-gray-800 shadow-md rounded-lg p-6 border border-gray-200 dark:border-gray-700">
            <p className="text-gray-600 dark:text-gray-300 mb-6">
              Enter your new password below.
            </p>
            
            <form onSubmit={handleSubmit}>
              <div className="mb-4">
                <label htmlFor="password" className="block text-sm font-medium mb-1">
                  New Password
                </label>
                <input
                  id="password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white"
                  required
                  minLength={6}
                />
              </div>
              
              <div className="mb-6">
                <label htmlFor="passwordConfirmation" className="block text-sm font-medium mb-1">
                  Confirm New Password
                </label>
                <input
                  id="passwordConfirmation"
                  type="password"
                  value={passwordConfirmation}
                  onChange={(e) => setPasswordConfirmation(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white"
                  required
                  minLength={6}
                />
              </div>
              
              <button
                type="submit"
                disabled={isSubmitting || !token}
                className={`w-full py-2 px-4 rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 ${
                  (isSubmitting || !token) ? 'opacity-70 cursor-not-allowed' : ''
                }`}
              >
                {isSubmitting ? 'Resetting...' : 'Reset Password'}
              </button>
              
              <div className="mt-4 text-center">
                <Link href="/login" className="text-sm text-blue-600 hover:underline">
                  Back to login
                </Link>
              </div>
            </form>
          </div>
        </>
      )}
    </div>
  )
}

// src/frontend/pages/reset-password.vue
<script setup>
import { ref, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useHead } from '#imports'
import { apiClient } from '~/api/api-client'

const password = ref('')
const passwordConfirmation = ref('')
const isSubmitting = ref(false)
const error = ref(null)
const success = ref(false)
const token = ref(null)
const router = useRouter()
const route = useRoute()

useHead({
  title: 'Reset Password | Certo',
})

onMounted(() => {
  token.value = route.query.code
  if (!token.value) {
    error.value = 'Reset token is missing. Please check your reset link.'
  }
})

async function handleSubmit() {
  if (password.value !== passwordConfirmation.value) {
    error.value = 'Passwords do not match.'
    return
  }
  if (!token.value) {
    error.value = 'Reset token is missing. Please check your reset link.'
    return
  }
  isSubmitting.value = true
  error.value = null
  try {
    await apiClient.post('/api/auth/reset-password', {
      code: token.value,
      password: password.value,
      passwordConfirmation: passwordConfirmation.value
    })
    success.value = true
    setTimeout(() => {
      router.push('/login')
    }, 3000)
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'An error occurred while resetting password'
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <div class="max-w-md mx-auto py-12 px-4">
    <h1 class="text-3xl font-bold text-center mb-8">Set New Password</h1>
    <NAlert v-if="success" variant="success" class="mb-4">
      <p>Your password has been reset successfully!</p>
      <p>You'll be redirected to the login page in a few seconds.</p>
      <div class="mt-4 text-center">
        <NButton @click="() => router.push('/login')" variant="outline">Go to login</NButton>
      </div>
    </NAlert>
    <template v-else>
      <NAlert v-if="error" variant="error" class="mb-4">{{ error }}</NAlert>
      <div class="bg-white dark:bg-gray-800 shadow-md rounded-lg p-6 border border-gray-200 dark:border-gray-700">
        <p class="text-gray-600 dark:text-gray-300 mb-6">
          Enter your new password below.
        </p>
        <form @submit.prevent="handleSubmit">
          <NFormItem label="New Password" required>
            <NInput
              v-model="password"
              type="password"
              placeholder="Enter new password"
              required
              minlength="6"
              :disabled="isSubmitting"
            />
          </NFormItem>
          <NFormItem label="Confirm New Password" required>
            <NInput
              v-model="passwordConfirmation"
              type="password"
              placeholder="Confirm new password"
              required
              minlength="6"
              :disabled="isSubmitting"
            />
          </NFormItem>
          <NButton
            type="submit"
            :loading="isSubmitting"
            class="w-full mt-4"
            :disabled="isSubmitting"
          >
            {{ isSubmitting ? 'Resetting...' : 'Reset Password' }}
          </NButton>
          <div class="mt-4 text-center">
            <NButton variant="link" @click="() => router.push('/login')">Back to login</NButton>
          </div>
        </form>
      </div>
    </template>
  </div>
</template>
