// src/frontend/pages/verify/index.vue
<script setup>
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import BadgeVerifier from '~/components/BadgeVerifier.vue'

const route = useRoute()
const id = ref('')

onMounted(() => {
  // Get the id from query params if present
  if (route.query.id) {
    id.value = route.query.id.toString()
  }
})

useHead({
  title: 'Verify Badge | Certo',
  meta: [
    { name: 'description', content: 'Verify Open Badges credentials' }
  ]
})
</script>

<template>
  <div class="container mx-auto py-10 px-4">
    <h1 class="text-3xl font-bold text-center mb-8">
      Open Badge Verification
    </h1>

    <ClientOnly>
      <BadgeVerifier :initial-identifier="id" />
      <template #fallback>
        <div class="text-center py-8">
          <div class="i-lucide-loader animate-spin w-8 h-8 mx-auto" />
          <p class="mt-4">
            Loading verification tool...
          </p>
        </div>
      </template>
    </ClientOnly>
  </div>
</template>

// src/frontend/src/app/verify/page.tsx
'use client'

import { Suspense } from 'react'
import { useSearchParams } from 'next/navigation'
import BadgeVerifier from '@/components/BadgeVerifier'

function VerifyPageContent() {
  const searchParams = useSearchParams()
  const id = searchParams.get('id') || ''

  return (
    <div className="max-w-4xl mx-auto">
      <BadgeVerifier initialIdentifier={id} />
    </div>
  )
}

export default function VerifyPage() {
  return (
    <div className="container mx-auto py-10 px-4">
      <h1 className="text-3xl font-bold text-center mb-8">
        Open Badge Verification
      </h1>
      <Suspense fallback={<div className="text-center">Loading...</div>}>
        <VerifyPageContent />
      </Suspense>
    </div>
  )
}
