// src/frontend/src/app/auth/forgot-password/page.tsx
'use client'

import { useState } from 'react'
import apiClient from '@/api/api-client'
import Link from 'next/link'

export default function ForgotPasswordPage() {
  const [email, setEmail] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsSubmitting(true)
    setError(null)
    
    try {
      await apiClient.post('/api/auth/forgot-password', { email })
      setSuccess(true)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred while requesting password reset')
      console.error('Password reset error:', err)
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="max-w-md mx-auto py-12 px-4">
      <h1 className="text-3xl font-bold text-center mb-8">Reset Password</h1>
      
      {success ? (
        <div className="bg-green-50 border border-green-200 text-green-800 rounded-md p-4 mb-4">
          <p>Password reset email sent! Please check your inbox for instructions to reset your password.</p>
          <p className="mt-4">
            <Link href="/login" className="text-blue-600 hover:underline">
              Return to login
            </Link>
          </p>
        </div>
      ) : (
        <>
          {error && (
            <div className="bg-red-50 border border-red-200 text-red-800 rounded-md p-4 mb-4">
              {error}
            </div>
          )}
          
          <div className="bg-white dark:bg-gray-800 shadow-md rounded-lg p-6 border border-gray-200 dark:border-gray-700">
            <p className="text-gray-600 dark:text-gray-300 mb-6">
              Enter your email address and we'll send you a link to reset your password.
            </p>
            
            <form onSubmit={handleSubmit}>
              <div className="mb-4">
                <label htmlFor="email" className="block text-sm font-medium mb-1">
                  Email Address
                </label>
                <input
                  id="email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white"
                  required
                />
              </div>
              
              <button
                type="submit"
                disabled={isSubmitting}
                className={`w-full py-2 px-4 rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 ${
                  isSubmitting ? 'opacity-70 cursor-not-allowed' : ''
                }`}
              >
                {isSubmitting ? 'Sending...' : 'Send Reset Link'}
              </button>
              
              <div className="mt-4 text-center">
                <Link href="/login" className="text-sm text-blue-600 hover:underline">
                  Back to login
                </Link>
              </div>
            </form>
          </div>
        </>
      )}
    </div>
  )
}

// src/frontend-una/pages/forgot-password.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useHead } from '#imports'

const email = ref('')
const isLoading = ref(false)
const success = ref(false)
const error = ref('')
const router = useRouter()

useHead({
  title: 'Forgot Password | Certo',
  meta: [
    { name: 'description', content: 'Reset your Certo account password.' }
  ]
})

async function handleSubmit() {
  error.value = ''
  isLoading.value = true
  success.value = false
  try {
    const res = await fetch('/api/auth/forgot-password', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: email.value })
    })
    if (!res.ok) {
      const data = await res.json().catch(() => ({}))
      throw new Error(data?.error?.message || 'Failed to send reset email')
    }
    success.value = true
  } catch (e: any) {
    error.value = e.message || 'Failed to send reset email'
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <main class="flex min-h-screen items-center justify-center bg-gray-50 dark:bg-gray-900 px-4">
    <div class="w-full max-w-md bg-white dark:bg-gray-800 rounded-lg shadow p-8">
      <h1 class="text-2xl font-bold mb-4 text-center">Forgot Password</h1>
      <p class="mb-6 text-gray-600 dark:text-gray-400 text-center">
        Enter your email address and we'll send you a link to reset your password.
      </p>
      <form @submit.prevent="handleSubmit" class="space-y-4">
        <div>
          <label for="email" class="block text-sm font-medium mb-1">Email</label>
          <input
            id="email"
            v-model="email"
            type="email"
            required
            class="w-full px-3 py-2 border rounded focus:outline-none focus:ring focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600"
            autocomplete="email"
            :disabled="isLoading"
          />
        </div>
        <button
          type="submit"
          class="w-full py-2 px-4 bg-primary-600 text-white rounded hover:bg-primary-700 disabled:opacity-50"
          :disabled="isLoading"
        >
          {{ isLoading ? 'Sending...' : 'Send Reset Link' }}
        </button>
      </form>
      <div v-if="success" class="mt-4 text-green-600 text-center">
        If an account exists for this email, a reset link has been sent.
      </div>
      <div v-if="error" class="mt-4 text-red-600 text-center">
        {{ error }}
      </div>
      <div class="mt-6 text-center">
        <NuxtLink to="/login" class="text-primary-600 hover:underline">Back to Login</NuxtLink>
      </div>
    </div>
  </main>
</template>
