// src/frontend/src/components/BadgeVerifier.tsx
'use client'

import { useState, useEffect } from 'react'
import { AchievementCredential, VerificationResult, VerificationCheck } from '../types/openbadges'
import apiClient from '../api/api-client'
import Image from 'next/image'

interface BadgeVerifierProps {
  initialIdentifier?: string
  autoVerify?: boolean
}

export const BadgeVerifier: React.FC<BadgeVerifierProps> = ({
  initialIdentifier = '',
  autoVerify = false,
}) => {
  const [identifier, setIdentifier] = useState(initialIdentifier)
  const [badge, setBadge] = useState<AchievementCredential | null>(null)
  const [rawCredential, setRawCredential] = useState<any | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [isVerified, setIsVerified] = useState<boolean | null>(null)
  const [verificationChecks, setVerificationChecks] = useState<VerificationCheck[] | null>(null)
  const [jsonInput, setJsonInput] = useState<string>('')
  const [verifyMode, setVerifyMode] = useState<'id' | 'json'>('id')

  // Auto-verify on mount if autoVerify is true and initialIdentifier is provided
  useEffect(() => {
    if (autoVerify && initialIdentifier) {
      verifyById()
    }
  }, [autoVerify, initialIdentifier])

  // Update identifier when initialIdentifier prop changes
  useEffect(() => {
    setIdentifier(initialIdentifier)
  }, [initialIdentifier])

  const handleVerify = async () => {
    if (verifyMode === 'id') {
      await verifyById()
    } else {
      await verifyByJson()
    }
  }

  const verifyById = async () => {
    if (!identifier.trim()) {
      setError('Please enter a credential identifier')
      return
    }

    setLoading(true)
    setError(null)
    setBadge(null)
    setRawCredential(null)
    setIsVerified(null)
    setVerificationChecks(null)

    try {
      const result = await apiClient.verifyBadge(identifier)
      setIsVerified(result.verified)
      setBadge(result.credential || null)
      setRawCredential(result.rawCredential || null)
      setVerificationChecks(result.checks || null)
      
      if (!result.verified && result.error) {
        setError(result.error)
      }
    } catch (err) {
      console.error('Error verifying badge:', err)
      setError('Failed to verify badge. Please check the identifier and try again.')
      setIsVerified(false)
    } finally {
      setLoading(false)
    }
  }

  const verifyByJson = async () => {
    if (!jsonInput.trim()) {
      setError('Please enter credential JSON')
      return
    }

    setLoading(true)
    setError(null)
    setBadge(null)
    setRawCredential(null)
    setIsVerified(null)
    setVerificationChecks(null)

    try {
      // Parse the JSON input
      let credentialData
      try {
        credentialData = JSON.parse(jsonInput)
      } catch (e) {
        throw new Error('Invalid JSON format. Please check your input.')
      }

      // Validate the credential
      const result = await apiClient.validateExternalBadge(credentialData)
      setIsVerified(result.verified)
      setBadge(result.credential || null)
      setRawCredential(result.rawCredential || null)
      setVerificationChecks(result.checks || null)
      
      if (!result.verified && result.error) {
        setError(result.error)
      }
    } catch (err) {
      console.error('Error validating badge:', err)
      setError(err instanceof Error ? err.message : 'Failed to validate badge.')
      setIsVerified(false)
    } finally {
      setLoading(false)
    }
  }

  const handleShare = async () => {
    if (!badge) return

    // Create share data
    const shareData = {
      title: `${badge.name || 'Achievement Badge'}`,
      text: `Check out my badge: ${badge.name}`,
      url: window.location.href,
    }

    try {
      if (navigator.share) {
        await navigator.share(shareData)
      } else {
        // Fallback - copy to clipboard
        await navigator.clipboard.writeText(window.location.href)
        alert('Link copied to clipboard')
      }
    } catch (err) {
      console.error('Error sharing:', err)
    }
  }

  return (
    <div className="w-full max-w-2xl mx-auto bg-white rounded-xl shadow-md overflow-hidden p-6">
      {!autoVerify && (
        <>
          <h2 className="text-2xl font-bold mb-4">Verify Open Badge</h2>
          
          <div className="mb-6">
            <div className="flex gap-4 mb-4">
              <button
                onClick={() => setVerifyMode('id')}
                className={`px-4 py-2 rounded-md ${
                  verifyMode === 'id' 
                    ? 'bg-blue-600 text-white' 
                    : 'bg-gray-200 text-gray-800 hover:bg-gray-300'
                }`}
              >
                Verify by ID
              </button>
              <button
                onClick={() => setVerifyMode('json')}
                className={`px-4 py-2 rounded-md ${
                  verifyMode === 'json' 
                    ? 'bg-blue-600 text-white' 
                    : 'bg-gray-200 text-gray-800 hover:bg-gray-300'
                }`}
              >
                Verify JSON
              </button>
            </div>

            {verifyMode === 'id' ? (
              <div className="flex gap-2">
                <input
                  type="text"
                  value={identifier}
                  onChange={(e) => setIdentifier(e.target.value)}
                  placeholder="Enter credential identifier"
                  className="flex-1 px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
                <button
                  onClick={handleVerify}
                  disabled={loading}
                  className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
                >
                  {loading ? 'Verifying...' : 'Verify'}
                </button>
              </div>
            ) : (
              <div className="flex flex-col gap-2">
                <textarea
                  value={jsonInput}
                  onChange={(e) => setJsonInput(e.target.value)}
                  placeholder="Paste credential JSON here"
                  rows={8}
                  className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono text-sm"
                />
                <button
                  onClick={handleVerify}
                  disabled={loading}
                  className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
                >
                  {loading ? 'Verifying...' : 'Verify JSON'}
                </button>
              </div>
            )}
          </div>
        </>
      )}

      {loading && <div className="text-center py-4">Verifying credential...</div>}

      {error && (
        <div className="mb-4 p-3 bg-red-50 text-red-700 rounded-md">{error}</div>
      )}

      {verificationChecks && (
        <div className="mb-4 p-3 bg-gray-50 rounded-md">
          <h3 className="font-semibold mb-2">Verification Checks</h3>
          <ul className="space-y-1">
            {verificationChecks.map((check, index) => (
              <li key={index} className="flex items-center">
                {check.result === 'success' ? (
                  <span className="text-green-600 mr-2">✓</span>
                ) : check.result === 'warning' ? (
                  <span className="text-yellow-600 mr-2">⚠</span>
                ) : (
                  <span className="text-red-600 mr-2">✗</span>
                )}
                <span className="capitalize">{check.check}</span>
                {check.message && <span className="ml-2 text-sm text-gray-500">({check.message})</span>}
              </li>
            ))}
          </ul>
        </div>
      )}

      {isVerified === false && !error && (
        <div className="mb-4 p-3 bg-red-50 text-red-700 rounded-md">
          Badge verification failed
        </div>
      )}

      {badge && (
        <div className="bg-gray-50 p-4 rounded-md">
          <div className="flex flex-col md:flex-row gap-6">
            {badge.image && (
              <div className="w-full md:w-1/3 flex-shrink-0">
                <div className="relative aspect-square w-full">
                  <Image
                    src={badge.image.id}
                    alt={badge.name || 'Badge image'}
                    fill
                    unoptimized
                    className="object-contain"
                  />
                </div>
              </div>
            )}
            
            <div className="flex-1">
              <div className="flex items-center mb-4">
                <h3 className="text-xl font-semibold mr-2">{badge.name}</h3>
                {isVerified ? (
                  <span className="bg-green-100 text-green-800 px-2 py-1 rounded-full text-xs font-medium">
                    ✓ Verified
                  </span>
                ) : (
                  <span className="bg-red-100 text-red-800 px-2 py-1 rounded-full text-xs font-medium">
                    ✗ Not Verified
                  </span>
                )}
              </div>
              
              <p className="text-gray-700 mb-4">{badge.description}</p>
              
              {/* Credential details section */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                <div>
                  <h4 className="text-sm font-semibold text-gray-500 mb-1">Issued By</h4>
                  <p className="font-medium">{badge.issuer.name}</p>
                  {badge.issuer.url && (
                    <a 
                      href={badge.issuer.url} 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="text-blue-600 text-sm hover:underline"
                    >
                      {badge.issuer.url}
                    </a>
                  )}
                </div>
                
                <div>
                  <h4 className="text-sm font-semibold text-gray-500 mb-1">Credential ID</h4>
                  <p className="text-sm font-mono overflow-hidden text-ellipsis">{rawCredential?.credentialId || badge.id}</p>
                </div>
                
                <div>
                  <h4 className="text-sm font-semibold text-gray-500 mb-1">Recipient</h4>
                  <p className="font-medium">{badge.recipient?.name || rawCredential?.recipient?.name || 'Not specified'}</p>
                  {(badge.recipient?.email || rawCredential?.recipient?.email) && (
                    <p className="text-sm text-gray-600">{badge.recipient?.email || rawCredential?.recipient?.email}</p>
                  )}
                </div>
                
                <div>
                  <h4 className="text-sm font-semibold text-gray-500 mb-1">Issuance Date</h4>
                  <p>{new Date(badge.issuanceDate).toLocaleDateString()}</p>
                </div>
                
                {badge.expirationDate && (
                  <div>
                    <h4 className="text-sm font-semibold text-gray-500 mb-1">Expiration Date</h4>
                    <p>{new Date(badge.expirationDate).toLocaleDateString()}</p>
                  </div>
                )}
              </div>
              
              {/* Certificate section */}
              {rawCredential?.id && (
                <div className="border-t border-gray-200 pt-4 mb-4">
                  <h4 className="font-semibold mb-2">Certificate</h4>
                  <div className="mt-2 flex flex-col items-center">
                    <div className="relative w-full max-w-md aspect-[4/3] border border-gray-200 rounded-md overflow-hidden mb-3">
                      <Image 
                        src={apiClient.getCertificateUrl(rawCredential.id)}
                        alt="Achievement Certificate"
                        fill
                        unoptimized
                        className="object-contain"
                      />
                    </div>
                    <a 
                      href={apiClient.getCertificateUrl(rawCredential.id)}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="mt-2 px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500"
                    >
                      Download Certificate
                    </a>
                  </div>
                </div>
              )}
              
              {/* Achievement data section */}
              {rawCredential?.achievement && (
                <div className="border-t border-gray-200 pt-4 mb-4">
                  <h4 className="font-semibold mb-2">Achievement Details</h4>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <h5 className="text-sm font-semibold text-gray-500 mb-1">Achievement Name</h5>
                      <p>{rawCredential.achievement.name}</p>
                    </div>
                    
                    {rawCredential.achievement.description && (
                      <div>
                        <h5 className="text-sm font-semibold text-gray-500 mb-1">Description</h5>
                        <p className="text-sm">{rawCredential.achievement.description}</p>
                      </div>
                    )}
                    
                    {rawCredential.achievement.criteria && (
                      <div className="col-span-2">
                        <h5 className="text-sm font-semibold text-gray-500 mb-1">Criteria</h5>
                        <p className="text-sm">{rawCredential.achievement.criteria.narrative}</p>
                      </div>
                    )}
                  </div>
                </div>
              )}
              
              {/* Evidence section */}
              {rawCredential?.evidence && rawCredential.evidence.length > 0 && (
                <div className="border-t border-gray-200 pt-4 mb-4">
                  <h4 className="font-semibold mb-2">Evidence</h4>
                  <div className="space-y-2">
                    {rawCredential.evidence.map((item: any, i: number) => (
                      <div key={i} className="bg-white p-2 rounded border border-gray-200">
                        <p className="font-medium">{item.name}</p>
                        {item.description && <p className="text-sm text-gray-700">{item.description}</p>}
                      </div>
                    ))}
                  </div>
                </div>
              )}
              
              <button
                onClick={handleShare}
                className="mt-4 px-4 py-2 bg-gray-800 text-white rounded-md hover:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-gray-500"
              >
                Share this Badge
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default BadgeVerifier

// src/frontend/app/components/BadgeVerifier.vue
<script setup>
import { apiClient } from '~/api/api-client'

const props = defineProps({
  initialIdentifier: {
    type: String,
    default: ''
  },
  autoVerify: {
    type: Boolean,
    default: false
  }
})

const identifier = ref(props.initialIdentifier)
const badge = ref(null)
const rawCredential = ref(null)
const loading = ref(false)
const error = ref(null)
const isVerified = ref(null)
const verificationChecks = ref(null)
const jsonInput = ref('')
const verifyMode = ref('id') // 'id' or 'json'
const fileError = ref(null)
const uploadedFileName = ref('')

// Auto-verify on mount if autoVerify is true and initialIdentifier is provided
onMounted(() => {
  if (props.autoVerify && props.initialIdentifier) {
    verifyById()
  }
})

// Update identifier when initialIdentifier prop changes
watch(() => props.initialIdentifier, (newVal) => {
  identifier.value = newVal
})

function setVerifyMode(mode) {
  verifyMode.value = mode
  error.value = null
  fileError.value = null
  isVerified.value = null
  badge.value = null
  rawCredential.value = null
  verificationChecks.value = null
  jsonInput.value = ''
  uploadedFileName.value = ''
}

async function handleFileUpload(event) {
  fileError.value = null
  const file = event.target.files && event.target.files[0]
  if (!file) {
    return
  }
  uploadedFileName.value = file.name
  if (file.type !== 'application/json') {
    fileError.value = 'Please upload a valid JSON file.'
    return
  }
  try {
    const text = await file.text()
    jsonInput.value = text
    // Try to parse for preview
    JSON.parse(text)
  }
  catch {
    fileError.value = 'Invalid JSON file.'
    jsonInput.value = ''
  }
}

function handleVerify() {
  if (verifyMode.value === 'id') {
    verifyById()
  }
  else {
    verifyByJson()
  }
}

async function verifyById() {
  if (!identifier.value.trim()) {
    error.value = 'Please enter a credential identifier'
    return
  }

  loading.value = true
  error.value = null
  badge.value = null
  rawCredential.value = null
  isVerified.value = null
  verificationChecks.value = null

  try {
    const result = await apiClient.verifyBadge(identifier.value)
    isVerified.value = result.verified
    badge.value = result.credential || null
    rawCredential.value = result.rawCredential || null
    verificationChecks.value = result.checks || null

    if (!result.verified && result.error) {
      error.value = result.error
    }
  }
  catch (err) {
    console.error('Error verifying badge:', err)
    error.value = 'Failed to verify badge. Please check the identifier and try again.'
    isVerified.value = false
  }
  finally {
    loading.value = false
  }
}

async function verifyByJson() {
  if (!jsonInput.value.trim()) {
    error.value = 'Please enter credential JSON'
    return
  }

  loading.value = true
  error.value = null
  badge.value = null
  rawCredential.value = null
  isVerified.value = null
  verificationChecks.value = null

  try {
    // Parse the JSON input
    let credentialData
    try {
      credentialData = JSON.parse(jsonInput.value)
    }
    catch {
      throw new Error('Invalid JSON format. Please check your input.')
    }

    // Validate the credential
    const result = await apiClient.validateExternalBadge(credentialData)
    isVerified.value = result.verified
    badge.value = result.credential || null
    rawCredential.value = result.rawCredential || null
    verificationChecks.value = result.checks || null

    if (!result.verified && result.error) {
      error.value = result.error
    }
  }
  catch (err) {
    console.error('Error validating badge:', err)
    error.value = err instanceof Error ? err.message : 'Failed to validate badge.'
    isVerified.value = false
  }
  finally {
    loading.value = false
  }
}

/*
function handleShare() {
  if (!badge.value) { return }

  // Create share data
  const shareData = {
    title: `${badge.value.name || 'Achievement Badge'}`,
    text: `Check out my badge: ${badge.value.name}`,
    url: window.location.href,
  }

  try {
    if (navigator.share) {
      navigator.share(shareData)
    }
    else {
      // Fallback - copy to clipboard
      navigator.clipboard.writeText(window.location.href)
      alert('Link copied to clipboard')
    }
  }
  catch (err) {
    console.error('Error sharing:', err)
  }
}
*/
</script>

<template>
  <div class="bg-white/80 backdrop-blur-lg rounded-2xl p-8 shadow-lg">
    <div class="text-center mb-8">
      <h2 class="text-2xl font-bold text-text-primary">
        Verify Certificate
      </h2>
      <p class="mt-2 text-text-secondary">
        Verify the authenticity of a certificate or badge
      </p>
    </div>

    <!-- Verification Mode Tabs -->
    <div class="flex justify-center mb-6 gap-4">
      <button
        type="button"
        class="px-4 py-2 rounded-full text-sm font-medium transition-colors" :class="[verifyMode === 'id' ? 'bg-[#5AB69F] text-black' : 'bg-gray-100 text-text-secondary hover:text-text-primary']"
        @click="setVerifyMode('id')"
      >
        By Certificate ID
      </button>
      <button
        type="button"
        class="px-4 py-2 rounded-full text-sm font-medium transition-colors" :class="[verifyMode === 'json' ? 'bg-[#5AB69F] text-black' : 'bg-gray-100 text-text-secondary hover:text-text-primary']"
        @click="setVerifyMode('json')"
      >
        By JSON File
      </button>
    </div>

    <!-- Verification Form -->
    <form class="space-y-6" @submit.prevent="handleVerify">
      <!-- Certificate ID Input -->
      <div v-if="verifyMode === 'id'">
        <label for="certificateId" class="block text-sm font-medium text-text-primary">
          Certificate ID or Hash
        </label>
        <div class="mt-1">
          <input
            id="certificateId"
            v-model="identifier"
            type="text"
            required
            class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-lg shadow-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#00E5C5] focus:border-transparent"
            placeholder="Enter certificate ID or hash"
          >
        </div>
      </div>

      <!-- File Upload & Preview -->
      <div v-if="verifyMode === 'json'">
        <label for="file-upload" class="block text-sm font-medium text-text-primary mb-2">
          Certificate JSON File
        </label>
        <div class="flex flex-col items-center justify-center px-6 py-4 border-2 border-dashed border-gray-300 rounded-lg hover:border-[#00E5C5] transition-colors">
          <div class="w-12 h-12 bg-[#00E5C5]/10 rounded-full flex items-center justify-center mb-4">
            <div class="w-6 h-6 i-heroicons-cloud-arrow-up text-[#5AB69F]" />
          </div>
          <label class="relative cursor-pointer rounded-md font-medium text-[#5AB69F] hover:text-[#5AB69F]/80 focus-within:outline-none">
            <span>Upload a file</span>
            <input
              id="file-upload"
              name="file-upload"
              type="file"
              class="sr-only"
              accept=".json"
              @change="handleFileUpload"
            >
          </label>
          <p class="pl-1">
            or drag and drop
          </p>
          <p class="text-xs text-text-secondary mt-2">
            Supports JSON files containing Open Badges or Verifiable Credentials
          </p>
          <div v-if="uploadedFileName" class="mt-2 text-xs text-text-secondary">
            Selected: {{ uploadedFileName }}
          </div>
          <div v-if="fileError" class="mt-2 text-xs text-red-600">
            {{ fileError }}
          </div>
        </div>
        <!-- Preview -->
        <div v-if="jsonInput && !fileError" class="mt-4 bg-gray-50 rounded-lg p-4 text-xs font-mono overflow-x-auto">
          <pre>{{ JSON.stringify(JSON.parse(jsonInput), null, 2) }}</pre>
        </div>
      </div>

      <!-- Submit Button -->
      <div>
        <button
          type="submit"
          :disabled="loading || (verifyMode === 'id' ? !identifier : !jsonInput || fileError)"
          class="w-full flex justify-center py-2 px-4 border border-transparent rounded-full shadow-sm text-black bg-[#5AB69F] hover:bg-[#5AB69F]/90 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[#00E5C5] disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <span v-if="!loading">Verify Certificate</span>
          <div v-else class="w-6 h-6 border-2 border-white border-t-transparent rounded-full animate-spin" />
        </button>
      </div>
    </form>

    <!-- Verification Result -->
    <div v-if="loading">
      <div class="flex justify-center py-8">
        <div class="i-lucide-loader animate-spin w-8 h-8" />
      </div>
    </div>

    <template v-else-if="error">
      <NAlert variant="error" class="mb-4">
        {{ error }}
      </NAlert>
    </template>

    <template v-else-if="isVerified !== null">
      <div class="mt-8">
        <div
          class="p-6 rounded-lg"
          :class="{
            'bg-green-50': isVerified,
            'bg-red-50': !isVerified,
          }"
        >
          <!-- Result Header -->
          <div class="flex items-center">
            <div
              class="w-12 h-12 rounded-full flex items-center justify-center"
              :class="{
                'bg-green-100': isVerified,
                'bg-red-100': !isVerified,
              }"
            >
              <div
                class="w-6 h-6"
                :class="{
                  'i-heroicons-check-circle text-green-600': isVerified,
                  'i-heroicons-x-circle text-red-600': !isVerified,
                }"
              />
            </div>
            <div class="ml-4">
              <h3
                class="text-lg font-medium"
                :class="{
                  'text-green-800': isVerified,
                  'text-red-800': !isVerified,
                }"
              >
                {{ isVerified ? 'Certificate Verified' : 'Verification Failed' }}
              </h3>
              <p
                class="text-sm"
                :class="{
                  'text-green-600': isVerified,
                  'text-red-600': !isVerified,
                }"
              >
                {{ verificationChecks && verificationChecks.length > 0 ? verificationChecks[0].message : error }}
              </p>
            </div>
          </div>

          <!-- Certificate Details -->
          <div v-if="isVerified" class="mt-6 space-y-4">
            <div class="flex items-center justify-between text-sm">
              <span class="text-text-secondary">Issuer</span>
              <span class="font-medium text-text-primary">{{ badge?.issuer?.name || 'Unknown Issuer' }}</span>
            </div>
            <div class="flex items-center justify-between text-sm">
              <span class="text-text-secondary">Issue Date</span>
              <span class="font-medium text-text-primary">{{ badge?.issuanceDate ? new Date(badge.issuanceDate).toLocaleDateString() : 'Unknown' }}</span>
            </div>
            <div v-if="badge?.expirationDate" class="flex items-center justify-between text-sm">
              <span class="text-text-secondary">Expiry Date</span>
              <span class="font-medium text-text-primary">{{ new Date(badge.expirationDate).toLocaleDateString() }}</span>
            </div>
            <div class="flex items-center justify-between text-sm">
              <span class="text-text-secondary">ID</span>
              <span class="font-medium text-text-primary">{{ badge?.id }}</span>
            </div>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>
