// src/frontend/src/app/auth/reset-password/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import apiClient from '@/api/api-client'
import Link from 'next/link'

export default function ResetPasswordPage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const [password, setPassword] = useState('')
  const [passwordConfirmation, setPasswordConfirmation] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState(false)
  const [token, setToken] = useState<string | null>(null)
  
  useEffect(() => {
    // Get code from URL query parameters
    const code = searchParams.get('code')
    if (code) {
      setToken(code)
    } else {
      setError('Reset token is missing. Please check your reset link.')
    }
  }, [searchParams])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (password !== passwordConfirmation) {
      setError('Passwords do not match.')
      return
    }
    
    if (!token) {
      setError('Reset token is missing. Please check your reset link.')
      return
    }
    
    setIsSubmitting(true)
    setError(null)
    
    try {
      await apiClient.post('/api/auth/reset-password', {
        code: token,
        password,
        passwordConfirmation
      })
      setSuccess(true)
      
      // Redirect to login after 3 seconds
      setTimeout(() => {
        router.push('/login')
      }, 3000)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred while resetting password')
      console.error('Password reset error:', err)
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="max-w-md mx-auto py-12 px-4">
      <h1 className="text-3xl font-bold text-center mb-8">Set New Password</h1>
      
      {success ? (
        <div className="bg-green-50 border border-green-200 text-green-800 rounded-md p-4 mb-4">
          <p>Your password has been reset successfully!</p>
          <p>You'll be redirected to the login page in a few seconds.</p>
          <p className="mt-4">
            <Link href="/login" className="text-blue-600 hover:underline">
              Go to login
            </Link>
          </p>
        </div>
      ) : (
        <>
          {error && (
            <div className="bg-red-50 border border-red-200 text-red-800 rounded-md p-4 mb-4">
              {error}
            </div>
          )}
          
          <div className="bg-white dark:bg-gray-800 shadow-md rounded-lg p-6 border border-gray-200 dark:border-gray-700">
            <p className="text-gray-600 dark:text-gray-300 mb-6">
              Enter your new password below.
            </p>
            
            <form onSubmit={handleSubmit}>
              <div className="mb-4">
                <label htmlFor="password" className="block text-sm font-medium mb-1">
                  New Password
                </label>
                <input
                  id="password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white"
                  required
                  minLength={6}
                />
              </div>
              
              <div className="mb-6">
                <label htmlFor="passwordConfirmation" className="block text-sm font-medium mb-1">
                  Confirm New Password
                </label>
                <input
                  id="passwordConfirmation"
                  type="password"
                  value={passwordConfirmation}
                  onChange={(e) => setPasswordConfirmation(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white"
                  required
                  minLength={6}
                />
              </div>
              
              <button
                type="submit"
                disabled={isSubmitting || !token}
                className={`w-full py-2 px-4 rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 ${
                  (isSubmitting || !token) ? 'opacity-70 cursor-not-allowed' : ''
                }`}
              >
                {isSubmitting ? 'Resetting...' : 'Reset Password'}
              </button>
              
              <div className="mt-4 text-center">
                <Link href="/login" className="text-sm text-blue-600 hover:underline">
                  Back to login
                </Link>
              </div>
            </form>
          </div>
        </>
      )}
    </div>
  )
}

// src/frontend/app/pages/reset-password.vue
<script setup lang="ts">
const { t } = useI18n()
const password = ref('')
const confirmPassword = ref('')
const isLoading = ref(false)
const success = ref(false)
const error = ref('')
const code = ref('')
const router = useRouter()
const route = useRoute()
const config = useRuntimeConfig()
const apiUrl = config.public.apiUrl
const pageDescription = ref('Set a new password for your Certo account.')

useSeoMeta({
  description: pageDescription.value,
  ogDescription: pageDescription.value,
  ogUrl: `${WEBSITE_URL}/reset-password`
})

useHead({
  title: 'Reset Password',
  link: [
    { rel: 'canonical', href: `${WEBSITE_URL}/reset-password` }
  ]
})

async function handleSubmit() {
  if (password.value !== confirmPassword.value) {
    error.value = 'Passwords do not match'
    return
  }

  if (!code.value) {
    error.value = 'Reset code is missing. Please check your reset link.'
    return
  }

  error.value = ''
  isLoading.value = true
  success.value = false

  try {
    const res = await fetch(`${apiUrl}/api/auth/reset-password`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        code: code.value,
        password: password.value,
        passwordConfirmation: confirmPassword.value
      })
    })

    if (!res.ok) {
      const data = await res.json().catch(() => ({}))
      throw new Error(data?.error?.message || 'Failed to reset password')
    }

    success.value = true
    // Redirect to login after 3 seconds
    setTimeout(() => {
      router.push('/login')
    }, 3000)
  }
  catch (e: any) {
    error.value = e.message || 'Failed to reset password'
  }
  finally {
    isLoading.value = false
  }
}

onMounted(() => {
  // Get the reset code from the URL
  code.value = route.query.code as string
  if (!code.value) {
    error.value = 'Reset code is missing. Please check your reset link.'
  }
})
</script>

<template>
  <div class="min-h-screen bg-gradient-to-b from-white to-[#FFE5AE]/20 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <!-- Header -->
      <div class="text-center">
        <h2 class="text-4xl font-bold text-text-primary">
          Set new password
        </h2>
        <p class="mt-2 text-text-secondary">
          Enter your new password below
        </p>
      </div>

      <!-- Form -->
      <div class="mt-8 bg-white/80 backdrop-blur-lg rounded-2xl p-8 shadow-lg">
        <!-- Success Message -->
        <div v-if="success" class="rounded-lg bg-green-50 p-4 mb-6">
          <div class="flex">
            <div class="flex-shrink-0">
              <div class="w-5 h-5 i-heroicons-check-circle text-green-400" />
            </div>
            <div class="ml-3">
              <p class="text-sm text-green-800">
                Your password has been reset successfully!
              </p>
              <p class="text-sm text-green-700 mt-1">
                Redirecting to login page in a few seconds...
              </p>
            </div>
          </div>
        </div>

        <!-- Error Message -->
        <div v-if="error" class="rounded-lg bg-red-50 p-4 mb-6">
          <div class="flex">
            <div class="flex-shrink-0">
              <div class="w-5 h-5 i-heroicons-x-circle text-red-400" />
            </div>
            <div class="ml-3">
              <p class="text-sm text-red-800">
                {{ error }}
              </p>
            </div>
          </div>
        </div>

        <form v-if="!success" class="space-y-6" @submit.prevent="handleSubmit">
          <!-- New Password -->
          <div>
            <label for="password" class="block text-sm font-medium text-text-primary">
              New password
            </label>
            <div class="mt-1">
              <input
                id="password"
                v-model="password"
                type="password"
                required
                minlength="6"
                class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-lg shadow-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#00E5C5] focus:border-transparent"
                placeholder="Enter new password"
                :disabled="isLoading"
                autocomplete="new-password"
              >
            </div>
          </div>

          <!-- Confirm Password -->
          <div>
            <label for="confirmPassword" class="block text-sm font-medium text-text-primary">
              Confirm new password
            </label>
            <div class="mt-1">
              <input
                id="confirmPassword"
                v-model="confirmPassword"
                type="password"
                required
                minlength="6"
                class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-lg shadow-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#00E5C5] focus:border-transparent"
                placeholder="Confirm new password"
                :disabled="isLoading"
                autocomplete="new-password"
              >
            </div>
          </div>

          <!-- Submit Button -->
          <button
            type="submit"
            :disabled="isLoading"
            class="w-full flex justify-center py-2 px-4 border border-transparent rounded-full shadow-sm text-white bg-[#00E5C5] hover:bg-[#00E5C5]/90 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[#00E5C5] disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <span v-if="!isLoading">Reset password</span>
            <div v-else class="w-6 h-6 border-2 border-white border-t-transparent rounded-full animate-spin" />
          </button>
        </form>

        <!-- Back to login -->
        <div class="mt-6 text-center">
          <p class="text-sm text-text-secondary">
            Remember your password?
            <NuxtLink to="/login" class="font-medium text-[#00E5C5] hover:text-[#00E5C5]/80">
              Sign in
            </NuxtLink>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>
