// src/frontend/components/CertificateCard.vue
<script setup>
defineOptions({
  name: 'CertificateCard'
})

import { ref, computed } from 'vue'
import { apiClient } from '~/api/api-client'
import { useRuntimeConfig } from '#app'

const props = defineProps({
  certificate: {
    type: Object,
    required: true
  },
  showRecipient: {
    type: Boolean,
    default: true
  }
})

const emit = defineEmits(['export', 'revoke', 'view', 'download'])

const isMenuOpen = ref(false)
const isRevoking = ref(false)
const revocationReason = ref('')
const isExporting = ref(false)

// Extract properties from the certificate with fallbacks for different data structures
const { 
  id,
  credentialId,
  achievement,
  issuer,
  recipient,
  issuanceDate,
  issuedOn,
  expirationDate,
  expires,
  revoked,
  image,
  description
} = props.certificate

// Get derived values with fallbacks
const achievementName = achievement?.name || props.certificate.name || 'Unknown Achievement'
const achievementDescription = description || achievement?.description || props.certificate.description || 'No description available'
const issuerName = issuer?.name || props.certificate.issuerName || 'Unknown Issuer'
const formattedIssuanceDate = formatDate(issuanceDate || issuedOn)
const formattedExpirationDate = expirationDate || expires ? formatDate(expirationDate || expires) : 'No expiration'

// Helper function to format dates
function formatDate(dateString) {
  if (!dateString) return 'Unknown'
  
  try {
    const date = new Date(dateString)
    return date.toLocaleDateString(undefined, { 
      year: 'numeric', 
      month: 'short', 
      day: 'numeric' 
    })
  } catch (error) {
    console.error('Error formatting date:', error)
    return dateString
  }
}

// Get the certificate image URL from the API
const imageUrl = computed(() => {
  const runtimeConfig = useRuntimeConfig()
  const apiUrl = runtimeConfig.public.apiUrl
  
  // Try different possible image structures
  if (props.certificate.imageUrl) {
    return props.certificate.imageUrl.startsWith('http') 
      ? props.certificate.imageUrl 
      : `${apiUrl}${props.certificate.imageUrl}`
  }
  
  if (image?.url) {
    return image.url.startsWith('http') 
      ? image.url 
      : `${apiUrl}${image.url}`
  }
  
  if (achievement?.image?.url) {
    return achievement.image.url.startsWith('http') 
      ? achievement.image.url 
      : `${apiUrl}${achievement.image.url}`
  }
  
  if (achievement?.image?.data?.attributes?.url) {
    return `${apiUrl}${achievement.image.data.attributes.url}`
  }
  
  if (props.certificate.attributes?.image?.data?.attributes?.url) {
    return `${apiUrl}${props.certificate.attributes.image.data.attributes.url}`
  }
  
  if (props.certificate.attributes?.achievement?.data?.attributes?.image?.data?.attributes?.url) {
    return `${apiUrl}${props.certificate.attributes.achievement.data.attributes.image.data.attributes.url}`
  }
  
  // Fallback to credential certificate endpoint
  return `${apiUrl}/api/credentials/${id}/certificate`
})

async function handleExport() {
  isExporting.value = true
  try {
    const exportData = await apiClient.exportCertificate(id)
    if (process.client) {
      // Create a download link for the exported certificate
      const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `certificate-${id}.json`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    }
    
    emit('export')
  } catch (error) {
    console.error('Error exporting certificate:', error)
  } finally {
    isExporting.value = false
  }
}

async function handleRevoke() {
  if (!revocationReason.value.trim()) return
  
  isRevoking.value = true
  try {
    await apiClient.revokeCertificate(id, revocationReason.value)
    emit('revoke')
  } catch (error) {
    console.error('Error revoking certificate:', error)
  } finally {
    isRevoking.value = false
    revocationReason.value = ''
  }
}

function getCredentialUrl() {
  // Use the browser's window.location to get the base URL
  const baseUrl = process.client 
    ? `${window.location.protocol}//${window.location.host}`
    : ''
  return `${baseUrl}/credentials/${encodeURIComponent(credentialId || id)}`
}

function getVerificationUrl() {
  // Use the browser's window.location to get the base URL
  const baseUrl = process.client 
    ? `${window.location.protocol}//${window.location.host}`
    : ''
  return `${baseUrl}/verify?id=${encodeURIComponent(credentialId || id)}`
}

function copyToClipboard() {
  if (!process.client) return
  
  try {
    const relativeUrl = `/credentials/${encodeURIComponent(credentialId || id)}`
    navigator.clipboard.writeText(relativeUrl)
    // Use the Una UI toast/notification instead of alert
    alert('Credential link copied to clipboard')
  } catch (error) {
    console.error('Error copying to clipboard:', error)
    alert('Failed to copy to clipboard')
  }
}

async function handleDownload() {
  if (!process.client || !imageUrl.value) return

  try {
    const a = document.createElement('a')
    a.href = imageUrl.value
    // Suggest a filename for the download
    a.download = `${achievementName.replace(/\s+/g, '-')}-certificate.png`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    emit('download')
  } catch (error) {
    console.error('Error downloading certificate image:', error)
    alert('Failed to download image.')
  }
}
</script>

<template>
  <div class="bg-white/80 backdrop-blur-lg rounded-2xl p-6 shadow-lg hover:shadow-xl transition-all">
    <div class="flex items-start justify-between">
      <div class="flex-1">
        <!-- Certificate Icon -->
        <div class="w-12 h-12 bg-[#00E5C5]/10 rounded-lg flex items-center justify-center mb-4">
          <div class="w-6 h-6 i-heroicons-document-text text-[#00E5C5]"></div>
        </div>

        <!-- Certificate Info -->
        <h3 class="text-lg font-medium text-text-primary mb-1">{{ achievementName }}</h3>
        <p class="text-text-secondary text-sm mb-4">{{ achievementDescription }}</p>

        <!-- Metadata -->
        <div class="space-y-2">
          <div class="flex items-center text-sm text-text-secondary">
            <div class="w-4 h-4 i-heroicons-calendar mr-2"></div>
            {{ formattedIssuanceDate }}
          </div>
          <div class="flex items-center text-sm text-text-secondary">
            <div class="w-4 h-4 i-heroicons-user mr-2"></div>
            {{ issuerName }}
          </div>
          <div v-if="showRecipient" class="flex items-center text-sm text-text-secondary">
            <div class="w-4 h-4 i-heroicons-building-office mr-2"></div>
            {{ recipient?.name || 'Unknown Recipient' }}
          </div>
        </div>
      </div>

      <!-- Dropdown Menu for Actions -->
      <div class="relative">
        <button 
          @click.stop="isMenuOpen = !isMenuOpen" 
          class="p-2 rounded-full hover:bg-gray-100"
        >
          <div class="w-5 h-5 i-heroicons-ellipsis-vertical text-gray-500"></div>
        </button>
        
        <!-- Dropdown Content -->
        <transition name="fade">
          <div 
            v-if="isMenuOpen" 
            class="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg z-10"
          >
            <a 
              :href="getCredentialUrl()" 
              target="_blank"
              class="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
            >
              View Certificate
            </a>
            <button 
              @click="handleDownload"
              class="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
            >
              Download
            </button>
            <button 
              @click="copyToClipboard"
              class="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
            >
              Copy Verification Link
            </button>
            <button 
              @click="handleExport" 
              :disabled="isExporting"
              class="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 disabled:opacity-50"
            >
              <span v-if="isExporting">Exporting...</span>
              <span v-else>Export to JSON</span>
            </button>
          </div>
        </transition>
      </div>
    </div>

    <!-- Image Preview -->
    <div class="mt-4 aspect-[16/9] bg-gray-100 rounded-lg flex items-center justify-center overflow-hidden">
      <img :src="imageUrl" alt="Certificate Image" class="w-full h-full object-cover">
    </div>
  </div>
</template>

// src/frontend/src/components/certificates/CertificateCard.tsx
'use client'

import Image from 'next/image'
import { useState } from 'react'
import { apiClient } from '@/api/api-client'
import Link from 'next/link'

interface CertificateCardProps {
  certificate: {
    id: string | number
    attributes: {
      name: string
      credentialId: string
      issuanceDate: string
      expirationDate?: string
      revoked: boolean
      image?: {
        data?: {
          attributes?: {
            url: string
          }
        }
      }
      achievement?: {
        data?: {
          attributes?: {
            name: string
            description?: string
          }
        }
      }
      issuer?: {
        data?: {
          attributes?: {
            name: string
          }
        }
      }
    }
  }
  onExport?: () => void
  onDelete?: () => void
  onRevoke?: () => void
}

export default function CertificateCard({ 
  certificate, 
  onExport, 
  onDelete, 
  onRevoke 
}: CertificateCardProps) {
  const [isRevoking, setIsRevoking] = useState(false)
  const [revocationReason, setRevocationReason] = useState('')
  const [isExporting, setIsExporting] = useState(false)
  const [isVerifying, setIsVerifying] = useState(false)

  const { 
    name, 
    credentialId, 
    issuanceDate, 
    expirationDate,
    revoked,
    image,
    achievement,
    issuer
  } = certificate.attributes

  const achievementName = achievement?.data?.attributes?.name || 'Unknown Achievement'
  const achievementDescription = achievement?.data?.attributes?.description || 'No description available'
  const issuerName = issuer?.data?.attributes?.name || 'Unknown Issuer'
  const imageUrl = image?.data?.attributes?.url || '/placeholder-badge.png'
  
  const formattedIssuanceDate = new Date(issuanceDate).toLocaleDateString()
  const formattedExpirationDate = expirationDate 
    ? new Date(expirationDate).toLocaleDateString() 
    : 'No expiration'

  const handleExport = async () => {
    if (!onExport) return
    
    setIsExporting(true)
    try {
      const exportData = await apiClient.exportCertificate(certificate.id)
      // Create a download link for the exported certificate
      const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `certificate-${certificate.id}.json`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
      
      onExport()
    } catch (error) {
      console.error('Error exporting certificate:', error)
    } finally {
      setIsExporting(false)
    }
  }

  const handleRevoke = async () => {
    if (!onRevoke || !revocationReason.trim()) return
    
    setIsRevoking(true)
    try {
      await apiClient.revokeCertificate(certificate.id, revocationReason)
      onRevoke()
    } catch (error) {
      console.error('Error revoking certificate:', error)
    } finally {
      setIsRevoking(false)
      setRevocationReason('')
    }
  }

  const getVerificationUrl = () => {
    // Use the browser's window.location to get the base URL
    const baseUrl = typeof window !== 'undefined' 
      ? `${window.location.protocol}//${window.location.host}`
      : ''
    return `${baseUrl}/verify?id=${encodeURIComponent(credentialId)}`
  }

  return (
    <div className="w-full max-w-md bg-white dark:bg-gray-800 rounded-lg shadow-md overflow-hidden">
      <div className="p-4">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center">
            <div className="flex-shrink-0 h-12 w-12 relative">
              <Image
                src={imageUrl}
                alt={name}
                fill
                className="rounded-md object-cover"
              />
            </div>
            <div className="ml-4">
              <h3 className="text-lg font-medium">{name}</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">{achievementName}</p>
            </div>
          </div>
          
          {revoked && (
            <span className="px-2 py-1 text-xs bg-red-100 text-red-800 rounded-full">
              Revoked
            </span>
          )}
        </div>
        
        <div className="mb-4">
          <p className="text-sm text-gray-600 dark:text-gray-300">{achievementDescription}</p>
        </div>
        
        <div className="grid grid-cols-2 gap-2 mb-4 text-sm">
          <div>
            <span className="font-medium">Issued by:</span>
            <p className="text-gray-600 dark:text-gray-400">{issuerName}</p>
          </div>
          <div>
            <span className="font-medium">Issued on:</span>
            <p className="text-gray-600 dark:text-gray-400">{formattedIssuanceDate}</p>
          </div>
          <div>
            <span className="font-medium">Expires:</span>
            <p className="text-gray-600 dark:text-gray-400">{formattedExpirationDate}</p>
          </div>
          <div>
            <span className="font-medium">ID:</span>
            <p className="text-gray-600 dark:text-gray-400 truncate">{credentialId}</p>
          </div>
        </div>
        
        <div className="flex flex-wrap gap-2">
          <Link 
            href={`/verify?id=${encodeURIComponent(credentialId)}`}
            className="px-3 py-1 text-sm bg-green-600 hover:bg-green-700 text-white rounded-md transition"
          >
            Verify
          </Link>

          {onExport && (
            <button
              onClick={handleExport}
              disabled={isExporting}
              className="px-3 py-1 text-sm bg-blue-600 hover:bg-blue-700 text-white rounded-md transition"
            >
              {isExporting ? 'Exporting...' : 'Export'}
            </button>
          )}
          
          {onDelete && (
            <button
              onClick={onDelete}
              className="px-3 py-1 text-sm bg-red-600 hover:bg-red-700 text-white rounded-md transition"
            >
              Delete
            </button>
          )}

          <button
            onClick={() => {
              // Copy verification URL to clipboard
              navigator.clipboard.writeText(getVerificationUrl())
              alert('Verification URL copied to clipboard')
            }}
            className="px-3 py-1 text-sm bg-gray-600 hover:bg-gray-700 text-white rounded-md transition"
          >
            Copy Link
          </button>
          
          {onRevoke && !revoked && (
            <div className="w-full mt-2">
              <div className="flex gap-2">
                <input
                  type="text"
                  value={revocationReason}
                  onChange={(e) => setRevocationReason(e.target.value)}
                  placeholder="Reason for revocation"
                  className="flex-1 px-2 py-1 text-sm border border-gray-300 dark:border-gray-700 rounded-md"
                />
                <button
                  onClick={handleRevoke}
                  disabled={isRevoking || !revocationReason.trim()}
                  className="px-3 py-1 text-sm bg-yellow-600 hover:bg-yellow-700 text-white rounded-md transition disabled:opacity-50"
                >
                  {isRevoking ? 'Revoking...' : 'Revoke'}
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
